python main.py elasticity \
    --tag elasticity2D_collide_hash_grid_5 \
    --num_hidden_layers 3 \
    --hidden_features 68 \
    -sr 100 \
    -vr 100 \
    -T 7 \
    -g 1 \
    --dt 0.1 \
    --max_n_iter 30000 \
    --lr 1e-5 \
    --dim 2 \
    --energy 'arap' 'kinematics' 'collision_sphere' 'external' 'volume' \
    --ratio_volume 1e3 \
    --ratio_arap 2e1 \
    --ratio_collide 1e4  \
    --ratio_kinematics 1e1 \
    -f_ext_x 0 \
    -f_ext_y ' -2e2' \
    -T_ext 2 \
    --early_stop \
    --n_levels 8 \
    --n_features_per_level 4 \
    --log2_hashmap_size 16 \
    --base_resolution 8 \
    --finest_resolution 128 \
    --mlp_unit "[68]" \
    --network hashgrid