python main.py fluid \
    --tag fluid2d_tlgnM_test \
    --init_cond taylorgreen_multi \
    --num_hidden_layers 3 \
    --hidden_features 32 \
    -sr 128 \
    -vr 32 \
    --max_n_iter 100 \
    --dt 0.05 \
    -T 100 \
    -g 0